spring:
  sql.init.mode: always
  datasource:
    hikari:
      maximum-pool-size: 4
      keepalive-time: 60000
      leak-detection-threshold: 60000
      data-source-properties:
        loginTimeout: 10
        socketTimeout: 60
  jpa:
    generate-ddl: true
    show-sql: false
    hibernate.ddl-auto: create
    open-in-view: true
    properties:
      javax.persistence.query.timeout: 60000
  transaction:
    default-timeout: 60s